-- Adds post titles and placeholder scores, plus comments for song posts.
-- Run this once in Supabase Dashboard > SQL Editor before using the updated app.

alter table public.song_posts
  add column if not exists song_title text,
  add column if not exists score numeric(5, 2) not null default 0
    check (score >= 0);

update public.song_posts
set song_title = file_name
where song_title is null or btrim(song_title) = '';

alter table public.song_posts
  alter column song_title set not null;

do $$
declare
  post_id_type text;
begin
  select format_type(attribute.atttypid, attribute.atttypmod)
    into post_id_type
  from pg_attribute as attribute
  where attribute.attrelid = 'public.song_posts'::regclass
    and attribute.attname = 'id'
    and not attribute.attisdropped;

  if post_id_type is null then
    raise exception 'Could not find public.song_posts.id';
  end if;

  execute format(
    'create table if not exists public.song_comments (
      id bigint generated by default as identity primary key,
      song_post_id %s not null references public.song_posts(id) on delete cascade,
      comment_text text not null check (
        char_length(btrim(comment_text)) between 1 and 1000
      ),
      created_at timestamptz not null default now()
    )',
    post_id_type
  );
end
$$;

create index if not exists song_comments_post_created_idx
  on public.song_comments (song_post_id, created_at);

alter table public.song_comments enable row level security;

drop policy if exists "Public can read song comments"
  on public.song_comments;
create policy "Public can read song comments"
  on public.song_comments for select to anon, authenticated
  using (true);

drop policy if exists "Public can add song comments"
  on public.song_comments;
create policy "Public can add song comments"
  on public.song_comments for insert to anon, authenticated
  with check (
    char_length(btrim(comment_text)) between 1 and 1000
  );

grant select, insert on public.song_comments to anon, authenticated;
grant usage, select on sequence public.song_comments_id_seq
  to anon, authenticated;
